# Generated by Django 5.1.15 on 2026-07-12 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("pdf_url", "PDF-URL"),
                            ("api", "API"),
                            ("manual", "Manuelle Eingabe"),
                            ("community", "Community-Erfassung"),
                        ],
                        max_length=20,
                        verbose_name="Quellentyp",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "parser_class",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Parser-Klasse"
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Konfiguration"
                    ),
                ),
            ],
            options={
                "verbose_name": "Datenquelle",
                "verbose_name_plural": "Datenquellen",
            },
        ),
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("downloading", "Lädt herunter"),
                            ("downloaded", "Heruntergeladen"),
                            ("parsing", "Wird verarbeitet"),
                            ("parsed", "Verarbeitet"),
                            ("validating", "Wird validiert"),
                            ("validated", "Validiert"),
                            ("failed", "Fehlgeschlagen"),
                            ("cancelled", "Abgebrochen"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(blank=True, max_length=64, verbose_name="SHA-256"),
                ),
                ("file_path", models.TextField(blank=True, verbose_name="Dateipfad")),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Dateigröße"
                    ),
                ),
                (
                    "detected_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Erkanntes Jahr"
                    ),
                ),
                ("parser_version", models.CharField(blank=True, max_length=20)),
                ("etag", models.CharField(blank=True, max_length=255)),
                ("last_modified", models.CharField(blank=True, max_length=100)),
                ("error_log", models.JSONField(blank=True, default=list)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_runs",
                        to="data_sources.datasource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import-Durchlauf",
                "verbose_name_plural": "Import-Durchläufe",
                "ordering": ["-created_at"],
            },
        ),
    ]
