# Generated by Django 5.2.4 on 2026-07-12 13:47

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Stadt',
                'verbose_name_plural': 'Städte',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='addresses.city')),
            ],
            options={
                'verbose_name': 'Ortsteil',
                'verbose_name_plural': 'Ortsteile',
                'ordering': ['name'],
                'unique_together': {('city', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=150)),
                ('postal_code', models.CharField(blank=True, max_length=5, verbose_name='PLZ')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Hinweis')),
                ('origin', models.CharField(choices=[('official_import', 'Offizieller PDF-Import'), ('admin', 'Administrator'), ('moderator', 'Moderator'), ('citizen', 'Bürgerbeitrag'), ('quorum', 'Quorum-bestätigt'), ('external_api', 'Externe API'), ('manual_import', 'Manueller Import')], default='official_import', max_length=30)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='addresses.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streets', to='addresses.district')),
            ],
            options={
                'verbose_name': 'Straße',
                'verbose_name_plural': 'Straßen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AddressKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=apps.core.models.generate_public_id, editable=False, max_length=16, unique=True)),
                ('house_number', models.PositiveIntegerField(blank=True, null=True)),
                ('suffix', models.CharField(blank=True, default='', max_length=5)),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_keys', to='addresses.street')),
            ],
            options={
                'verbose_name': 'Adressschlüssel',
                'verbose_name_plural': 'Adressschlüssel',
            },
        ),
        migrations.CreateModel(
            name='StreetAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Alternative Schreibweise')),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=150)),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='addresses.street')),
            ],
            options={
                'verbose_name': 'Straßen-Alias',
                'verbose_name_plural': 'Straßen-Aliasse',
            },
        ),
        migrations.CreateModel(
            name='StreetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hausnummer von')),
                ('house_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hausnummer bis (leer = offen)')),
                ('parity', models.CharField(choices=[('all', 'alle Hausnummern'), ('odd', 'ungerade'), ('even', 'gerade')], default='all', max_length=5, verbose_name='Seite')),
                ('raw_range', models.CharField(blank=True, help_text='Unveränderte Bereichsangabe aus der Quelle, z. B. „1-32/43“.', max_length=100, verbose_name='Original-Bereichsangabe')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Hinweis')),
                ('origin', models.CharField(choices=[('official_import', 'Offizieller PDF-Import'), ('admin', 'Administrator'), ('moderator', 'Moderator'), ('citizen', 'Bürgerbeitrag'), ('quorum', 'Quorum-bestätigt'), ('external_api', 'Externe API'), ('manual_import', 'Manueller Import')], default='official_import', max_length=30)),
                ('status', models.CharField(choices=[('active', 'aktiv'), ('pending', 'in Prüfung'), ('retired', 'außer Kraft')], default='active', max_length=10)),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Gültig ab')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='addresses.street')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='schedules.collectionzone')),
            ],
            options={
                'verbose_name': 'Tourenzuordnung',
                'verbose_name_plural': 'Tourenzuordnungen',
                'ordering': ['street__name', 'house_from'],
            },
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['city', 'normalized_name'], name='addresses_s_city_id_87f58c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='addresskey',
            unique_together={('street', 'house_number', 'suffix')},
        ),
    ]
