# Generated by Django 5.2.4 on 2026-07-12 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="street",
            name="bms_street_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Straßen-ID im Online-Abfallkalender (insert-it.de).",
                null=True,
                verbose_name="BMS-Straßen-ID",
            ),
        ),
        migrations.CreateModel(
            name="HouseNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=20, verbose_name="Hausnummer")),
                (
                    "number",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("suffix", models.CharField(blank=True, default="", max_length=10)),
                (
                    "bms_location_id",
                    models.IntegerField(db_index=True, verbose_name="BMS-Location-ID"),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("official_import", "Offizieller PDF-Import"),
                            ("admin", "Administrator"),
                            ("moderator", "Moderator"),
                            ("citizen", "Bürgerbeitrag"),
                            ("quorum", "Quorum-bestätigt"),
                            ("external_api", "Externe API"),
                            ("manual_import", "Manueller Import"),
                        ],
                        default="external_api",
                        max_length=30,
                    ),
                ),
                (
                    "street",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="house_numbers",
                        to="addresses.street",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hausnummer",
                "verbose_name_plural": "Hausnummern",
                "ordering": ["number", "suffix", "text"],
                "unique_together": {("street", "text")},
            },
        ),
    ]
