# Generated by Django 5.2.4 on 2026-07-13 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_street_bms_street_id_housenumber"),
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housenumber",
            name="origin",
            field=models.CharField(
                choices=[
                    ("official_import", "Offizieller PDF-Import"),
                    ("admin", "Administrator"),
                    ("moderator", "Moderator"),
                    ("citizen", "Bürgerbeitrag"),
                    ("quorum", "Quorum-bestätigt"),
                    ("external_api", "Externe API"),
                    ("manual_import", "Manueller Import"),
                ],
                default="external_api",
                max_length=30,
                verbose_name="Herkunft",
            ),
        ),
        migrations.AlterField(
            model_name="housenumber",
            name="street",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="house_numbers",
                to="addresses.street",
                verbose_name="Straße",
            ),
        ),
        migrations.AlterField(
            model_name="street",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="streets",
                to="addresses.city",
                verbose_name="Stadt",
            ),
        ),
        migrations.AlterField(
            model_name="street",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="streets",
                to="addresses.district",
                verbose_name="Ortsteil",
            ),
        ),
        migrations.AlterField(
            model_name="street",
            name="origin",
            field=models.CharField(
                choices=[
                    ("official_import", "Offizieller PDF-Import"),
                    ("admin", "Administrator"),
                    ("moderator", "Moderator"),
                    ("citizen", "Bürgerbeitrag"),
                    ("quorum", "Quorum-bestätigt"),
                    ("external_api", "Externe API"),
                    ("manual_import", "Manueller Import"),
                ],
                default="official_import",
                max_length=30,
                verbose_name="Herkunft",
            ),
        ),
        migrations.AlterField(
            model_name="streetassignment",
            name="origin",
            field=models.CharField(
                choices=[
                    ("official_import", "Offizieller PDF-Import"),
                    ("admin", "Administrator"),
                    ("moderator", "Moderator"),
                    ("citizen", "Bürgerbeitrag"),
                    ("quorum", "Quorum-bestätigt"),
                    ("external_api", "Externe API"),
                    ("manual_import", "Manueller Import"),
                ],
                default="official_import",
                max_length=30,
                verbose_name="Herkunft",
            ),
        ),
        migrations.AlterField(
            model_name="streetassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "aktiv"),
                    ("pending", "in Prüfung"),
                    ("retired", "außer Kraft"),
                ],
                default="active",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="streetassignment",
            name="street",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="addresses.street",
                verbose_name="Straße",
            ),
        ),
        migrations.AlterField(
            model_name="streetassignment",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="schedules.collectionzone",
                verbose_name="Bezirk",
            ),
        ),
    ]
