# Generated by Django 5.2.4 on 2026-07-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "addresses",
            "0003_alter_housenumber_origin_alter_housenumber_street_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="street",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Für die öffentliche Straßen-Seite (/strasse/<slug>/).",
                max_length=180,
                null=True,
                unique=True,
                verbose_name="URL-Slug",
            ),
        ),
    ]
