# Generated by Django 5.2.4 on 2026-07-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0004_street_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streetassignment",
            name="raw_range",
            field=models.CharField(
                blank=True,
                help_text="Unveränderte Bereichsangabe aus der Quelle, z. B. „1-32/43“.",
                max_length=255,
                verbose_name="Original-Bereichsangabe",
            ),
        ),
    ]
