# Generated by Django 5.1.15 on 2026-07-12 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("waste_types", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "search_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Suchname"
                    ),
                ),
                (
                    "postal_codes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="PLZ (kommasepariert)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ortsteil",
                "verbose_name_plural": "Ortsteile",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CollectionZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "letter",
                    models.CharField(
                        help_text="Einzelbuchstabe (A-J) oder Kombination (B/G)",
                        max_length=5,
                        verbose_name="Buchstabe",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="Name"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "waste_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="waste_types.wastetype",
                        verbose_name="Abfallart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abfuhrbezirk",
                "verbose_name_plural": "Abfuhrbezirke",
                "ordering": ["letter"],
                "unique_together": {("letter", "waste_type")},
            },
        ),
        migrations.CreateModel(
            name="Street",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("pdf_import", "Offizieller PDF-Import"),
                            ("admin", "Administrator"),
                            ("moderator", "Moderator"),
                            ("citizen", "Bürgerbeitrag"),
                            ("quorum", "Quorum"),
                            ("external_api", "Externe API"),
                            ("manual", "Manueller Import"),
                        ],
                        default="admin",
                        max_length=20,
                    ),
                ),
                ("source_detail", models.CharField(blank=True, max_length=255)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Straßenname")),
                (
                    "search_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Normalisierter Suchname",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=10, verbose_name="PLZ"),
                ),
                (
                    "city",
                    models.CharField(
                        default="Lübeck", max_length=100, verbose_name="Stadt"
                    ),
                ),
                (
                    "has_number_ranges",
                    models.BooleanField(
                        default=True, verbose_name="Hat Hausnummernbereiche"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Hinweise")),
                ("version", models.IntegerField(default=1, verbose_name="Version")),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="streets",
                        to="addresses.district",
                        verbose_name="Ortsteil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Straße",
                "verbose_name_plural": "Straßen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AddressKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Öffentliche ID"
                    ),
                ),
                ("house_number", models.CharField(blank=True, max_length=10)),
                ("house_number_suffix", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "street",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_keys",
                        to="addresses.street",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adressschlüssel",
                "verbose_name_plural": "Adressschlüssel",
            },
        ),
        migrations.CreateModel(
            name="StreetAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alias",
                    models.CharField(max_length=255, verbose_name="Alternativname"),
                ),
                (
                    "search_alias",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Normalisierter Alias"
                    ),
                ),
                (
                    "street",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="addresses.street",
                    ),
                ),
            ],
            options={
                "verbose_name": "Straßenalias",
                "verbose_name_plural": "Straßenaliase",
            },
        ),
        migrations.CreateModel(
            name="StreetAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("pdf_import", "Offizieller PDF-Import"),
                            ("admin", "Administrator"),
                            ("moderator", "Moderator"),
                            ("citizen", "Bürgerbeitrag"),
                            ("quorum", "Quorum"),
                            ("external_api", "Externe API"),
                            ("manual", "Manueller Import"),
                        ],
                        default="admin",
                        max_length=20,
                    ),
                ),
                ("source_detail", models.CharField(blank=True, max_length=255)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "house_number_start",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Hausnummer von"
                    ),
                ),
                (
                    "house_number_end",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Hausnummer bis"
                    ),
                ),
                (
                    "house_number_parity",
                    models.CharField(
                        choices=[
                            ("all", "Alle"),
                            ("even", "Gerade"),
                            ("odd", "Ungerade"),
                        ],
                        default="all",
                        max_length=5,
                        verbose_name="Hausnummern-Parität",
                    ),
                ),
                (
                    "house_number_suffix",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Hausnummernzusatz"
                    ),
                ),
                (
                    "location_note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ortshinweis"
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(blank=True, null=True, verbose_name="Gültig ab"),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="Gültig bis"),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="Priorität")),
                ("version", models.IntegerField(default=1)),
                (
                    "override_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overrides",
                        to="addresses.streetassignment",
                        verbose_name="Überschreibt",
                    ),
                ),
                (
                    "street",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="addresses.street",
                        verbose_name="Straße",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="addresses.collectionzone",
                        verbose_name="Abfuhrbezirk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Straßenzuordnung",
                "verbose_name_plural": "Straßenzuordnungen",
            },
        ),
        migrations.AddIndex(
            model_name="street",
            index=models.Index(
                fields=["search_name"], name="addresses_s_search__e267ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="street",
            index=models.Index(fields=["name"], name="addresses_s_name_648f68_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="addresskey",
            unique_together={("street", "house_number", "house_number_suffix")},
        ),
        migrations.AddIndex(
            model_name="streetassignment",
            index=models.Index(
                fields=["street", "zone"], name="addresses_s_street__29992b_idx"
            ),
        ),
    ]
