# Generated by Django 5.1.15 on 2026-07-12 15:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("check_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("warning", "Warnung"),
                            ("error", "Fehler"),
                            ("unknown", "Unbekannt"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("checked_at", models.DateTimeField(auto_now=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "System-Check",
                "verbose_name_plural": "System-Checks",
                "ordering": ["-checked_at"],
            },
        ),
    ]
