# Generated by Django 5.2.4 on 2026-07-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='fas fa-trash', max_length=100, verbose_name='Icon (Font-Awesome-Klasse)')),
                ('color', models.CharField(default='#f2c200', max_length=9, verbose_name='Farbe (Hex)')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('ics_summary', models.CharField(blank=True, max_length=100, verbose_name='ICS-Titel')),
                ('ics_description', models.TextField(blank=True, default='Abholung für {address}. Bitte rechtzeitig bereitstellen.', verbose_name='ICS-Beschreibung')),
                ('reminder_hours_before', models.PositiveIntegerField(default=0, verbose_name='Erinnerung (Stunden vorher, 0 = keine)')),
            ],
            options={
                'verbose_name': 'Abfallart',
                'verbose_name_plural': 'Abfallarten',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
