# Generated by Django 5.1.15 on 2026-07-12 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addresses", "0001_initial"),
        ("schedules", "0001_initial"),
        ("waste_types", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityContribution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.CharField(blank=True, max_length=20, unique=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Jahr")),
                ("collection_date", models.DateField(verbose_name="Abfuhrdatum")),
                ("house_number_start", models.CharField(blank=True, max_length=10)),
                ("house_number_end", models.CharField(blank=True, max_length=10)),
                ("source", models.TextField(blank=True, verbose_name="Quelle")),
                ("notes", models.TextField(blank=True, verbose_name="Anmerkungen")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("submitted", "Eingereicht"),
                            ("duplicate", "Duplikat"),
                            ("awaiting_confirmation", "Bestätigungen ausstehend"),
                            ("quorum_reached", "Quorum erreicht"),
                            ("under_review", "In Prüfung"),
                            ("accepted", "Angenommen"),
                            ("partially_accepted", "Teilweise angenommen"),
                            ("rejected", "Abgelehnt"),
                            ("published", "Veröffentlicht"),
                            ("withdrawn", "Zurückgezogen"),
                        ],
                        default="draft",
                        max_length=25,
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, upload_to="community/%Y/", verbose_name="Foto/Beleg"
                    ),
                ),
                (
                    "street",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="addresses.street",
                        verbose_name="Straße",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "waste_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waste_types.wastetype",
                        verbose_name="Abfallart",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="addresses.collectionzone",
                        verbose_name="Abfuhrbezirk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Community-Beitrag",
                "verbose_name_plural": "Community-Beiträge",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ErrorReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.CharField(blank=True, max_length=20, unique=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("wrong_date", "Falscher Termin"),
                            ("missing_date", "Fehlender Termin"),
                            ("wrong_zone", "Falscher Abfuhrbezirk"),
                            ("wrong_street_assignment", "Falsche Straßenzuordnung"),
                            ("wrong_number_range", "Falscher Hausnummernbereich"),
                            ("street_missing", "Straße fehlt"),
                            ("wrong_district", "Falscher Ortsteil"),
                            ("pdf_import_error", "Fehlerhafter PDF-Import"),
                            ("calendar_feed_broken", "Kalenderfeed funktioniert nicht"),
                            ("short_term_change", "Kurzfristige Terminänderung"),
                            ("other", "Sonstiges Problem"),
                        ],
                        max_length=30,
                        verbose_name="Kategorie",
                    ),
                ),
                ("description", models.TextField(verbose_name="Beschreibung")),
                (
                    "suggested_correction",
                    models.TextField(blank=True, verbose_name="Korrekturvorschlag"),
                ),
                (
                    "source_info",
                    models.TextField(blank=True, verbose_name="Quellenangabe"),
                ),
                (
                    "reporter_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="E-Mail (optional für Rückfragen)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Neu"),
                            ("under_review", "In Prüfung"),
                            ("accepted", "Angenommen"),
                            ("rejected", "Abgelehnt"),
                            ("duplicate", "Duplikat"),
                            ("resolved", "Gelöst"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "moderator_comment",
                    models.TextField(blank=True, verbose_name="Moderatoren-Kommentar"),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "affected_date",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="schedules.collectiondate",
                        verbose_name="Betroffener Termin",
                    ),
                ),
                (
                    "affected_street",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="addresses.street",
                        verbose_name="Betroffene Straße",
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="community.errorreport",
                        verbose_name="Duplikat von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fehlermeldung",
                "verbose_name_plural": "Fehlermeldungen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CorrectionProposal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.CharField(blank=True, max_length=20, unique=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("collection_date", "Abfuhrtermin"),
                            ("zone", "Abfuhrbezirk"),
                            ("street_assignment", "Straßenzuordnung"),
                            ("street", "Straße"),
                            ("district", "Ortsteil"),
                            ("house_number_range", "Hausnummernbereich"),
                        ],
                        max_length=30,
                        verbose_name="Zieltyp",
                    ),
                ),
                (
                    "target_id",
                    models.UUIDField(blank=True, null=True, verbose_name="Ziel-ID"),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Alter Wert"
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(default=dict, verbose_name="Neuer Wert"),
                ),
                ("reason", models.TextField(verbose_name="Begründung")),
                ("source", models.TextField(blank=True, verbose_name="Quelle")),
                (
                    "confidence",
                    models.IntegerField(
                        default=5, verbose_name="Vertrauensstufe (1-10)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Neu"),
                            ("duplicate", "Duplikat"),
                            ("awaiting_confirmation", "Bestätigungen ausstehend"),
                            ("under_review", "In Prüfung"),
                            ("accepted", "Angenommen"),
                            ("partially_accepted", "Teilweise angenommen"),
                            ("rejected", "Abgelehnt"),
                            ("implemented", "Umgesetzt"),
                            ("superseded", "Durch Import überholt"),
                        ],
                        default="new",
                        max_length=25,
                    ),
                ),
                (
                    "votes_needed",
                    models.IntegerField(
                        default=3, verbose_name="Benötigte Bestätigungen"
                    ),
                ),
                (
                    "votes_yes",
                    models.IntegerField(default=1, verbose_name="Positive Stimmen"),
                ),
                (
                    "votes_no",
                    models.IntegerField(default=0, verbose_name="Negative Stimmen"),
                ),
                (
                    "moderator_decision",
                    models.TextField(
                        blank=True, verbose_name="Entscheidungsbegründung"
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_proposals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Moderator",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ersteller",
                    ),
                ),
                (
                    "similar_proposals",
                    models.ManyToManyField(
                        blank=True,
                        to="community.correctionproposal",
                        verbose_name="Ähnliche Vorschläge",
                    ),
                ),
                (
                    "error_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="community.errorreport",
                        verbose_name="Zugehörige Fehlermeldung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Korrekturvorschlag",
                "verbose_name_plural": "Korrekturvorschläge",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProposalVote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Session (anonym)"
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[("yes", "Dafür"), ("no", "Dagegen")],
                        max_length=5,
                        verbose_name="Stimme",
                    ),
                ),
                ("weight", models.IntegerField(default=1, verbose_name="Gewichtung")),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="community.correctionproposal",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Abstimmung",
                "verbose_name_plural": "Abstimmungen",
                "unique_together": {("proposal", "session_key"), ("proposal", "voter")},
            },
        ),
        migrations.CreateModel(
            name="QuorumRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("collection_date", "Abfuhrtermin"),
                            ("zone", "Abfuhrbezirk"),
                            ("street_assignment", "Straßenzuordnung"),
                            ("street", "Straße"),
                            ("district", "Ortsteil"),
                            ("house_number_range", "Hausnummernbereich"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "min_votes",
                    models.IntegerField(default=3, verbose_name="Minimale Stimmen"),
                ),
                (
                    "min_independent_voters",
                    models.IntegerField(
                        default=3, verbose_name="Min. unabhängige Abstimmende"
                    ),
                ),
                (
                    "voting_period_days",
                    models.IntegerField(
                        default=14, verbose_name="Abstimmungszeitraum (Tage)"
                    ),
                ),
                (
                    "requires_source",
                    models.BooleanField(
                        default=False, verbose_name="Quelle erforderlich"
                    ),
                ),
                (
                    "min_confidence",
                    models.IntegerField(
                        default=1, verbose_name="Min. Vertrauensniveau"
                    ),
                ),
                (
                    "waste_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quorum_rules",
                        to="waste_types.wastetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quorum-Regel",
                "verbose_name_plural": "Quorum-Regeln",
                "unique_together": {("waste_type", "target_type")},
            },
        ),
    ]
