# Generated by Django 5.2.4 on 2026-07-12 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waste_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('kind', models.CharField(choices=[('pdf_url', 'PDF-Abruf per URL'), ('manual', 'Manuelle Pflege'), ('community', 'Community-Erfassung'), ('api', 'Externe API')], default='pdf_url', max_length=20, verbose_name='Art')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('parser_key', models.CharField(blank=True, help_text='Registrierter Parser-Schlüssel, z. B. „luebeck_gelber_sack“.', max_length=100, verbose_name='Parser')),
                ('check_interval_hours', models.PositiveIntegerField(default=24, verbose_name='Prüfintervall (Stunden)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('last_checked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_status', models.CharField(blank=True, editable=False, max_length=200)),
                ('last_etag', models.CharField(blank=True, editable=False, max_length=200)),
                ('last_modified_header', models.CharField(blank=True, editable=False, max_length=100)),
                ('last_sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='waste_types.wastetype')),
            ],
            options={
                'verbose_name': 'Datenquelle',
                'verbose_name_plural': 'Datenquellen',
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='source_documents/%Y/', verbose_name='Datei')),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('etag', models.CharField(blank=True, max_length=200)),
                ('last_modified_header', models.CharField(blank=True, max_length=100)),
                ('fetched_at', models.DateTimeField(verbose_name='Abgerufen am')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('detected_year', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('archived', 'archiviert'), ('active', 'aktuelle Version'), ('superseded', 'abgelöst')], default='active', max_length=20)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='data_sources.datasource')),
            ],
            options={
                'verbose_name': 'Quelldokument',
                'verbose_name_plural': 'Quelldokumente',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
