# Generated by Django 5.2.4 on 2026-07-13 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_sources", "0001_initial"),
        ("waste_types", "0003_seed_bms_waste_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="waste_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_sources",
                to="waste_types.wastetype",
                verbose_name="Abfallart",
            ),
        ),
        migrations.AlterField(
            model_name="sourcedocument",
            name="data_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="data_sources.datasource",
                verbose_name="Datenquelle",
            ),
        ),
        migrations.AlterField(
            model_name="sourcedocument",
            name="detected_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Erkanntes Jahr"
            ),
        ),
        migrations.AlterField(
            model_name="sourcedocument",
            name="page_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Seiten"
            ),
        ),
        migrations.AlterField(
            model_name="sourcedocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("archived", "archiviert"),
                    ("active", "aktuelle Version"),
                    ("superseded", "abgelöst"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
