# Generated by Django 5.1.15 on 2026-07-12 15:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WasteType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "icon_name",
                    models.CharField(
                        default="bi-trash", max_length=50, verbose_name="Icon"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#6c757d", max_length=7, verbose_name="Farbe (Hex)"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="Sortierung"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "has_collection_zones",
                    models.BooleanField(default=True, verbose_name="Hat Abfuhrbezirke"),
                ),
                (
                    "quorum_config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Quorum-Konfiguration"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Abfallart",
                "verbose_name_plural": "Abfallarten",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
