# Generated by Django 5.1.15 on 2026-07-12 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addresses", "0001_initial"),
        ("data_sources", "0001_initial"),
        ("waste_types", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleYear",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Jahr")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("discovered", "Entdeckt"),
                            ("downloaded", "Heruntergeladen"),
                            ("parsing", "Wird verarbeitet"),
                            ("parse_failed", "Verarbeitung fehlgeschlagen"),
                            ("parsed", "Verarbeitet"),
                            ("validation_failed", "Validierung fehlgeschlagen"),
                            ("needs_review", "Benötigt Prüfung"),
                            ("approved", "Freigegeben"),
                            ("published", "Veröffentlicht"),
                            ("superseded", "Ersetzt"),
                            ("withdrawn", "Zurückgezogen"),
                            ("archived", "Archiviert"),
                        ],
                        default="discovered",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Veröffentlicht am"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Anmerkungen")),
                (
                    "statistics",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Statistiken"
                    ),
                ),
                (
                    "import_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_years",
                        to="data_sources.importrun",
                        verbose_name="Import-Durchlauf",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_years",
                        to="schedules.scheduleyear",
                        verbose_name="Ersetzt durch",
                    ),
                ),
                (
                    "waste_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_years",
                        to="waste_types.wastetype",
                        verbose_name="Abfallart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jahresplan",
                "verbose_name_plural": "Jahrespläne",
                "ordering": ["-year"],
                "unique_together": {("waste_type", "year")},
            },
        ),
        migrations.CreateModel(
            name="CollectionDate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("pdf_import", "Offizieller PDF-Import"),
                            ("admin", "Administrator"),
                            ("moderator", "Moderator"),
                            ("citizen", "Bürgerbeitrag"),
                            ("quorum", "Quorum"),
                            ("external_api", "Externe API"),
                            ("manual", "Manueller Import"),
                        ],
                        default="admin",
                        max_length=20,
                    ),
                ),
                ("source_detail", models.CharField(blank=True, max_length=255)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("collection_date", models.DateField(verbose_name="Abfuhrdatum")),
                (
                    "is_special",
                    models.BooleanField(default=False, verbose_name="Sondertermin"),
                ),
                ("note", models.TextField(blank=True, verbose_name="Hinweis")),
                (
                    "manual_override",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overridden_dates",
                        to="schedules.collectiondate",
                        verbose_name="Manuelle Überschreibung",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_dates",
                        to="addresses.collectionzone",
                        verbose_name="Abfuhrbezirk",
                    ),
                ),
                (
                    "schedule_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_dates",
                        to="schedules.scheduleyear",
                        verbose_name="Jahresplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abfuhrtermin",
                "verbose_name_plural": "Abfuhrtermine",
                "ordering": ["collection_date"],
                "indexes": [
                    models.Index(
                        fields=["collection_date"],
                        name="schedules_c_collect_a33252_idx",
                    ),
                    models.Index(
                        fields=["zone", "collection_date"],
                        name="schedules_c_zone_id_0cecae_idx",
                    ),
                    models.Index(
                        fields=["schedule_year", "zone"],
                        name="schedules_c_schedul_9d520b_idx",
                    ),
                ],
            },
        ),
    ]
