# Generated by Django 5.1.15 on 2026-07-12 15:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsAggregate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("hour", "Stündlich"),
                            ("day", "Täglich"),
                            ("week", "Wöchentlich"),
                            ("month", "Monatlich"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("event_type", models.CharField(blank=True, max_length=40)),
                ("district_id", models.CharField(blank=True, max_length=50)),
                ("street_id", models.CharField(blank=True, max_length=50)),
                ("waste_type_slug", models.CharField(blank=True, max_length=50)),
                ("count", models.IntegerField(default=0)),
                ("unique_sessions", models.IntegerField(default=0)),
                ("data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Aggregierte Daten",
                "verbose_name_plural": "Aggregierte Daten",
                "indexes": [
                    models.Index(
                        fields=["period", "period_start"],
                        name="analytics_a_period_f5e83f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Seitenaufruf"),
                            ("street_search", "Straßensuche"),
                            ("street_search_no_result", "Suche ohne Ergebnis"),
                            ("address_resolved", "Adresse aufgelöst"),
                            ("schedule_view", "Terminansicht"),
                            ("calendar_subscription_page_view", "Kalender-Abo-Seite"),
                            ("calendar_feed_requested", "Kalender-Feed abgerufen"),
                            ("calendar_downloaded", "Kalender heruntergeladen"),
                            ("error_report_opened", "Fehlermeldung geöffnet"),
                            ("error_report_submitted", "Fehlermeldung eingereicht"),
                            ("correction_submitted", "Korrektur eingereicht"),
                            ("proposal_confirmed", "Vorschlag bestätigt"),
                            (
                                "community_entry_submitted",
                                "Community-Beitrag eingereicht",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "session_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("district_id", models.CharField(blank=True, max_length=50)),
                ("street_id", models.CharField(blank=True, max_length=50)),
                ("address_key_id", models.CharField(blank=True, max_length=50)),
                ("waste_type_slug", models.CharField(blank=True, max_length=50)),
                ("calendar_year", models.IntegerField(blank=True, null=True)),
                (
                    "device_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("desktop", "Desktop"),
                            ("tablet", "Tablet"),
                            ("mobile", "Mobil"),
                        ],
                        max_length=10,
                    ),
                ),
                ("browser_family", models.CharField(blank=True, max_length=50)),
                ("referrer_host", models.CharField(blank=True, max_length=255)),
                ("result_status", models.CharField(blank=True, max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Analytics-Ereignis",
                "verbose_name_plural": "Analytics-Ereignisse",
                "indexes": [
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="analytics_a_event_t_64745b_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="analytics_a_timesta_aef2a5_idx"
                    ),
                ],
            },
        ),
    ]
