# Generated by Django 5.2.4 on 2026-07-12 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('waste_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('dimension', models.CharField(default='total', help_text='z. B. total, district:12, street:1023, waste:gelber-sack, client:Google Kalender', max_length=150)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Aggregat',
                'verbose_name_plural': 'Aggregate',
                'unique_together': {('date', 'event_type', 'dimension')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Seitenaufruf'), ('street_search', 'Straßensuche'), ('street_search_no_result', 'Suche ohne Ergebnis'), ('address_resolved', 'Adresse aufgelöst'), ('schedule_view', 'Terminansicht'), ('calendar_subscription_page_view', 'Abo-Seite'), ('calendar_feed_requested', 'Kalenderfeed abgerufen'), ('calendar_downloaded', 'Kalender heruntergeladen'), ('error_report_opened', 'Fehlerformular geöffnet'), ('error_report_submitted', 'Fehlermeldung abgesendet'), ('correction_submitted', 'Korrektur vorgeschlagen'), ('proposal_confirmed', 'Vorschlag bestätigt'), ('community_entry_submitted', 'Community-Eintrag')], db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_hash', models.CharField(blank=True, max_length=32)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('device_class', models.CharField(blank=True, max_length=20)),
                ('browser_family', models.CharField(blank=True, max_length=30)),
                ('calendar_client', models.CharField(blank=True, max_length=50)),
                ('referrer_domain', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('query', models.CharField(blank=True, max_length=100)),
                ('address_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.addresskey')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.district')),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.street')),
                ('waste_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste_types.wastetype')),
            ],
            options={
                'verbose_name': 'Nutzungsereignis',
                'verbose_name_plural': 'Nutzungsereignisse',
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_a_event_t_6c35be_idx')],
            },
        ),
    ]
