# Generated by Django 5.2.4 on 2026-07-12 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parser_key', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('schedule', 'Jahresplan'), ('streets', 'Straßenliste'), ('full', 'Vollständig')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('running', 'läuft'), ('parse_failed', 'Verarbeitung fehlgeschlagen'), ('validation_failed', 'Validierung fehlgeschlagen'), ('needs_review', 'Prüfung erforderlich'), ('completed', 'abgeschlossen'), ('rejected', 'verworfen')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('log', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_runs', to='data_sources.sourcedocument')),
            ],
            options={
                'verbose_name': 'Importlauf',
                'verbose_name_plural': 'Importläufe',
                'ordering': ['-started_at'],
            },
        ),
    ]
