# Generated by Django 5.2.4 on 2026-07-13 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_sources", "0002_alter_datasource_waste_type_and_more"),
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importrun",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Beendet"),
        ),
        migrations.AlterField(
            model_name="importrun",
            name="kind",
            field=models.CharField(
                choices=[
                    ("schedule", "Jahresplan"),
                    ("streets", "Straßenliste"),
                    ("full", "Vollständig"),
                ],
                default="full",
                max_length=20,
                verbose_name="Art",
            ),
        ),
        migrations.AlterField(
            model_name="importrun",
            name="parser_key",
            field=models.CharField(max_length=100, verbose_name="Parser"),
        ),
        migrations.AlterField(
            model_name="importrun",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_runs",
                to="data_sources.sourcedocument",
                verbose_name="Quelldokument",
            ),
        ),
        migrations.AlterField(
            model_name="importrun",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Gestartet"),
        ),
        migrations.AlterField(
            model_name="importrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "läuft"),
                    ("parse_failed", "Verarbeitung fehlgeschlagen"),
                    ("validation_failed", "Validierung fehlgeschlagen"),
                    ("needs_review", "Prüfung erforderlich"),
                    ("completed", "abgeschlossen"),
                    ("rejected", "verworfen"),
                ],
                default="running",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
