# Generated by Django 5.2.4 on 2026-07-12 13:47

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('schedules', '0001_initial'),
        ('waste_types', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('zone_code', models.CharField(blank=True, max_length=10)),
                ('street_text', models.CharField(blank=True, max_length=150, verbose_name='Straße')),
                ('district_text', models.CharField(blank=True, max_length=100, verbose_name='Ortsteil')),
                ('house_range', models.CharField(blank=True, max_length=100, verbose_name='Hausnummernbereich')),
                ('note', models.TextField(blank=True, verbose_name='Anmerkung')),
                ('source_hint', models.CharField(blank=True, max_length=255, verbose_name='Quelle')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='community_evidence/%Y/', verbose_name='Beleg (Foto/Dokument)')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('session_hash', models.CharField(blank=True, editable=False, max_length=32)),
                ('status', models.CharField(choices=[('submitted', 'eingereicht'), ('accepted', 'übernommen'), ('rejected', 'abgelehnt'), ('expired', 'verfallen')], default='submitted', max_length=20)),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_types.wastetype')),
            ],
            options={
                'verbose_name': 'Community-Beitrag',
                'verbose_name_plural': 'Community-Beiträge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('date_move', 'Termin verschieben'), ('date_add', 'Termin hinzufügen'), ('date_remove', 'Termin entfernen'), ('zone_change', 'Tourenbuchstaben ändern'), ('house_range_change', 'Hausnummernbereich ändern'), ('street_add', 'Straße ergänzen'), ('district_fix', 'Ortsteil korrigieren'), ('spelling_fix', 'Schreibweise ändern'), ('note', 'Hinweis')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('submitted', 'eingereicht'), ('duplicate', 'Duplikat'), ('awaiting_confirmation', 'wartet auf Bestätigungen'), ('quorum_reached', 'Quorum erreicht'), ('under_review', 'in Prüfung'), ('accepted', 'angenommen'), ('partially_accepted', 'teilweise angenommen'), ('rejected', 'abgelehnt'), ('published', 'umgesetzt'), ('withdrawn', 'zurückgezogen'), ('superseded', 'durch offiziellen Import überholt')], default='submitted', max_length=30)),
                ('old_value', models.JSONField(blank=True, default=dict, verbose_name='Bisheriger Wert')),
                ('new_value', models.JSONField(blank=True, default=dict, verbose_name='Vorgeschlagener Wert')),
                ('reason', models.TextField(verbose_name='Begründung')),
                ('source_url', models.URLField(blank=True, verbose_name='Quelle (optional)')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('session_hash', models.CharField(blank=True, editable=False, max_length=32)),
                ('confirmations', models.PositiveIntegerField(default=0, editable=False)),
                ('objections', models.PositiveIntegerField(default=0, editable=False)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('collection_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.collectiondate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_proposals', to=settings.AUTH_USER_MODEL)),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.street')),
                ('waste_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste_types.wastetype')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.collectionzone')),
            ],
            options={
                'verbose_name': 'Korrekturvorschlag',
                'verbose_name_plural': 'Korrekturvorschläge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_token', models.CharField(default=apps.core.models.generate_token, editable=False, max_length=12, unique=True)),
                ('category', models.CharField(choices=[('wrong_date', 'Falscher Termin'), ('missing_date', 'Fehlender Termin'), ('wrong_zone', 'Falscher Abfuhrbezirk'), ('wrong_street_assignment', 'Falsche Straßenzuordnung'), ('wrong_house_range', 'Falscher Hausnummernbereich'), ('street_missing', 'Straße fehlt'), ('wrong_district', 'Falscher Ortsteil'), ('import_error', 'Fehlerhafter PDF-Import'), ('feed_broken', 'Kalenderfeed funktioniert nicht'), ('short_notice_change', 'Kurzfristige Terminänderung'), ('other', 'Sonstiges Problem')], max_length=40)),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('source_hint', models.CharField(blank=True, max_length=255, verbose_name='Quelle (optional)')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail für Rückfragen (optional)')),
                ('status', models.CharField(choices=[('new', 'neu'), ('duplicate', 'Duplikat'), ('in_review', 'in Prüfung'), ('answered', 'beantwortet'), ('resolved', 'gelöst'), ('rejected', 'abgelehnt')], default='new', max_length=20)),
                ('public_response', models.TextField(blank=True, verbose_name='Öffentliche Antwort')),
                ('internal_note', models.TextField(blank=True, verbose_name='Interne Notiz')),
                ('session_hash', models.CharField(blank=True, editable=False, max_length=32)),
                ('address_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.addresskey')),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.street')),
                ('waste_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste_types.wastetype')),
            ],
            options={
                'verbose_name': 'Fehlermeldung',
                'verbose_name_plural': 'Fehlermeldungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuorumRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_kind', models.CharField(choices=[('date_move', 'Termin verschieben'), ('date_add', 'Termin hinzufügen'), ('date_remove', 'Termin entfernen'), ('zone_change', 'Tourenbuchstaben ändern'), ('house_range_change', 'Hausnummernbereich ändern'), ('street_add', 'Straße ergänzen'), ('district_fix', 'Ortsteil korrigieren'), ('spelling_fix', 'Schreibweise ändern'), ('note', 'Hinweis')], max_length=30)),
                ('min_confirmations', models.PositiveIntegerField(default=5, verbose_name='Benötigte Bestätigungen')),
                ('max_objection_ratio', models.FloatField(default=0.25, help_text='0.25 = Quorum scheitert, wenn mehr als 25 % Gegenstimmen vorliegen.', verbose_name='Maximaler Gegenstimmen-Anteil')),
                ('requires_source', models.BooleanField(default=False, verbose_name='Quelle erforderlich')),
                ('window_days', models.PositiveIntegerField(default=30, verbose_name='Zeitfenster (Tage)')),
                ('auto_publish', models.BooleanField(default=False, help_text='Nur wirksam, wenn der Community-Modus global aktiviert ist (§22).', verbose_name='Automatisch veröffentlichen')),
                ('is_active', models.BooleanField(default=True)),
                ('waste_type', models.ForeignKey(blank=True, help_text='Leer = gilt für alle Abfallarten.', null=True, on_delete=django.db.models.deletion.CASCADE, to='waste_types.wastetype')),
            ],
            options={
                'verbose_name': 'Quorum-Regel',
                'verbose_name_plural': 'Quorum-Regeln',
            },
        ),
        migrations.CreateModel(
            name='ProposalVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_hash', models.CharField(max_length=32)),
                ('is_support', models.BooleanField(default=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community.correctionproposal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bestätigung',
                'verbose_name_plural': 'Bestätigungen',
                'unique_together': {('proposal', 'session_hash')},
            },
        ),
    ]
