# Generated by Django 5.2.4 on 2026-07-12 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_sources', '0001_initial'),
        ('imports', '0001_initial'),
        ('waste_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, verbose_name='Kennung')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='waste_types.wastetype')),
            ],
            options={
                'verbose_name': 'Abfuhrbezirk',
                'verbose_name_plural': 'Abfuhrbezirke',
                'ordering': ['waste_type', 'code'],
                'unique_together': {('waste_type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(verbose_name='Kalenderjahr')),
                ('status', models.CharField(choices=[('discovered', 'entdeckt'), ('downloaded', 'heruntergeladen'), ('parsing', 'wird verarbeitet'), ('parse_failed', 'Verarbeitung fehlgeschlagen'), ('parsed', 'verarbeitet'), ('validation_failed', 'Validierung fehlgeschlagen'), ('needs_review', 'Prüfung erforderlich'), ('approved', 'freigegeben'), ('published', 'veröffentlicht'), ('superseded', 'abgelöst'), ('withdrawn', 'zurückgezogen'), ('archived', 'archiviert')], default='discovered', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Veröffentlicht am')),
                ('notes', models.TextField(blank=True, verbose_name='Interne Notizen')),
                ('import_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_years', to='imports.importrun')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_years', to='data_sources.sourcedocument')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_years', to='waste_types.wastetype')),
            ],
            options={
                'verbose_name': 'Jahresplan',
                'verbose_name_plural': 'Jahrespläne',
                'ordering': ['-year'],
                'unique_together': {('waste_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CollectionDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='Datum')),
                ('kind', models.CharField(choices=[('regular', 'regulär'), ('shifted', 'verschoben (Feiertag)'), ('special', 'Sondertermin')], default='regular', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Hinweis')),
                ('origin', models.CharField(choices=[('official_import', 'Offizieller PDF-Import'), ('admin', 'Administrator'), ('moderator', 'Moderator'), ('citizen', 'Bürgerbeitrag'), ('quorum', 'Quorum-bestätigt'), ('external_api', 'Externe API'), ('manual_import', 'Manueller Import')], default='official_import', max_length=30)),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Entfällt')),
                ('sequence', models.PositiveIntegerField(default=0, help_text='ICS SEQUENCE, wird bei Änderungen erhöht.')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='schedules.collectionzone')),
                ('schedule_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='schedules.scheduleyear')),
            ],
            options={
                'verbose_name': 'Abfuhrtermin',
                'verbose_name_plural': 'Abfuhrtermine',
                'ordering': ['date'],
                'unique_together': {('schedule_year', 'zone', 'date')},
            },
        ),
    ]
