# Generated by Django 5.2.4 on 2026-07-13 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_sources", "0002_alter_datasource_waste_type_and_more"),
        ("imports", "0002_alter_importrun_finished_at_alter_importrun_kind_and_more"),
        ("schedules", "0001_initial"),
        ("waste_types", "0003_seed_bms_waste_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectiondate",
            name="kind",
            field=models.CharField(
                choices=[
                    ("regular", "regulär"),
                    ("shifted", "verschoben (Feiertag)"),
                    ("special", "Sondertermin"),
                ],
                default="regular",
                max_length=10,
                verbose_name="Art",
            ),
        ),
        migrations.AlterField(
            model_name="collectiondate",
            name="origin",
            field=models.CharField(
                choices=[
                    ("official_import", "Offizieller PDF-Import"),
                    ("admin", "Administrator"),
                    ("moderator", "Moderator"),
                    ("citizen", "Bürgerbeitrag"),
                    ("quorum", "Quorum-bestätigt"),
                    ("external_api", "Externe API"),
                    ("manual_import", "Manueller Import"),
                ],
                default="official_import",
                max_length=30,
                verbose_name="Herkunft",
            ),
        ),
        migrations.AlterField(
            model_name="collectiondate",
            name="schedule_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dates",
                to="schedules.scheduleyear",
                verbose_name="Jahresplan",
            ),
        ),
        migrations.AlterField(
            model_name="collectiondate",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dates",
                to="schedules.collectionzone",
                verbose_name="Bezirk",
            ),
        ),
        migrations.AlterField(
            model_name="collectionzone",
            name="waste_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zones",
                to="waste_types.wastetype",
                verbose_name="Abfallart",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleyear",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedule_years",
                to="imports.importrun",
                verbose_name="Importlauf",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleyear",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedule_years",
                to="data_sources.sourcedocument",
                verbose_name="Quelldokument",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleyear",
            name="status",
            field=models.CharField(
                choices=[
                    ("discovered", "entdeckt"),
                    ("downloaded", "heruntergeladen"),
                    ("parsing", "wird verarbeitet"),
                    ("parse_failed", "Verarbeitung fehlgeschlagen"),
                    ("parsed", "verarbeitet"),
                    ("validation_failed", "Validierung fehlgeschlagen"),
                    ("needs_review", "Prüfung erforderlich"),
                    ("approved", "freigegeben"),
                    ("published", "veröffentlicht"),
                    ("superseded", "abgelöst"),
                    ("withdrawn", "zurückgezogen"),
                    ("archived", "archiviert"),
                ],
                default="discovered",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleyear",
            name="waste_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_years",
                to="waste_types.wastetype",
                verbose_name="Abfallart",
            ),
        ),
    ]
